test/tests.coffee

some basic stuff, I guess that "more red than green" is a good sign, hope it won't get hard to read in exchange :-)

 some simplification peillis/helpapp#3455

---

test/test_client.coffee
test/test_widget.coffee

ok, the first results tests. learnt something about DOMMutation events.
I really hope I'm done debugging and fighting with the DOM..

 #3455 ok, first results widget test

---

src/controller.coffee
test/test_client.coffee
test/test_widget.coffee

step by step: two widgets down, three to go

3455 write unit tests: results widget tests

---

test/test_controller.coffee

 #3405 first steps with controller test

---

test/test_controller.coffee

3455 write unit tests

---

.travis.yml
package.json

this is just for testing. do nothing

3840 add travis to js doofinder

---

CHANGELOG.md
src/widgets/pager.coffee

@carlosescri this is needed for peillis/js-layers/pull/320
I put the changes on `CHANGELOG.md` as "unreleased"
my guess is that you'll run `grunt release` when you merge this PR?

 dont escape nextLabel and previousLabel

---

src/util/is.ts
test/test_util_is.ts

- isNull does not actually add too much
- Added missing introspection functions
These will be removed from [doofinder/webcomponents](/doofinder/webcomponents).

refactor: introspection utils

---

src/query.ts

refactor: deleted reset method and save initial config functionality

---

src/query.ts

fix: save text in load method

---

src/util/encode-params.ts
test/test_util_encode-params.ts

fix: remove undefined values from query params

---

playground/getitems.html
playground/index.html
src/client.ts
src/query.ts
src/stats.ts
src/util/validators.ts
test/test_query_builder.ts
test/test_stats_client.ts
test/test_validators.ts

I've used the same method as for text queries because we said we would have one method per endpoint.

get items request

---

src/query/query.ts
test/test_query_builder.ts

feat: paginate items in query dump

---

doofinder.api.md
src/client.ts
test/test_client.ts

refactor: remove options call

---

.travis.yml

fix: fix tests

---

docs/Gemfile.lock

Reverts doofinder/js-doofinder#253

Revert "build(deps): bump nokogiri from 1.10.7 to 1.10.9 in /docs"

---

src/response.ts
test/fixtures/basic_response.ts
test/test_response.ts

Fix: #266 
Related to: https://github.com/doofinder/webcomponents/issues/539

Rename facet attribute from score to order

---

README.md
doofinder.api.md
src/query/sort.ts
test/test_query_builder.ts

Add has method to QuerySort

---

doofinder.api.md
playground/demo.js
playground/getitems.html
playground/module.html
playground/query.html
playground/standalone.html
src/stats.ts
test/test_stats_client.ts

Related #12473 https://github.com/doofinder/helpapp/issues/12473

improvement: added title/price for addtocart

---

README.md

related to https://github.com/doofinder/doomanager/issues/8638

Update link for admin panel
